<a href="https://colab.research.google.com/github/SurekhaBerlin/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [2]:

import numpy as np



In [3]:
a = np.array([1,2,3])

In [4]:
type(a)

numpy.ndarray

In [5]:
len(a)

3

In [6]:
b = np.array([1,2,3],dtype = float)

In [7]:
b

array([1., 2., 3.])

In [8]:
b.ndim

1

In [9]:
b.shape


(3,)

In [10]:
b.dtype

dtype('float64')

Accessing Elements

In [15]:
a = np.array([[1,2,3,4,5],[11,12,13,14,15]])

In [16]:
a[0,4] = 50

In [17]:
a

array([[ 1,  2,  3,  4, 50],
       [11, 12, 13, 14, 15]])

#####zeros , ones , Full and some random methods

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [24]:
np.random.rand(4,4)

array([[0.04769189, 0.35067322, 0.88817446, 0.59643882],
       [0.05635691, 0.47187553, 0.70140151, 0.74999271],
       [0.54580899, 0.47647101, 0.54681336, 0.83775962],
       [0.65982196, 0.25944555, 0.54049904, 0.77873107]])

In [25]:
np.random.randint(1,400,size = (4,4))

array([[297, 337,  22,  50],
       [314, 102, 148, 174],
       [280, 200, 210, 199],
       [ 65, 373,  73,  87]])

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a = np.array([[1,2,3,4,5],
              [11,12,13,14,15],
              [10,20,30,40,50],
              [9,8,7,6,5],
              [12,22,32,42,52]])

In [28]:
a

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [10, 20, 30, 40, 50],
       [ 9,  8,  7,  6,  5],
       [12, 22, 32, 42, 52]])

In [36]:
a[:2,-3:]

array([[ 3,  4,  5],
       [13, 14, 15]])

In [37]:
a[3,2]

7

In [38]:
a[:2,2:]

array([[ 3,  4,  5],
       [13, 14, 15]])

In [39]:
import numpy as np
a = np.zeros((3,3),dtype = int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [43]:
a[3//2,:] = 1
a[:,3//2] = 1
print(a)

[[0 1 0]
 [1 1 1]
 [0 1 0]]


In [47]:
import numpy as np
a = np.zeros((3,3),dtype = int)
a[3//2,:] = 1
a[:,3//2] = 1
print(a)

[[0 1 0]
 [1 1 1]
 [0 1 0]]


In [48]:
import numpy as np
a = np.zeros((5,5),dtype = int)
a[5//2,:] = 1
a[:,5//2] = 1
print(a)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [49]:
import numpy as np
a = np.zeros((3,3),dtype = int)
a[1,:] = 1
a[:,1] = 1
print(a)

[[0 1 0]
 [1 1 1]
 [0 1 0]]


In [50]:
import numpy as np
a = np.zeros((5,5),dtype = int)
a[2,:] = 1
a[:,2] = 1
print(a)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [81]:
def crossIdentity(n):

  if n%2 == 0 or n<0 or n==1:
    print("Enter an odd positive number greater than 2")

  else:
    a = np.zeros((n,n),dtype = int)
    a[n//2,:] = 1
    a[:,n//2] = 1
    return a


In [82]:
crossIdentity(4)

Enter an odd positive number greater than 2


In [84]:
crossIdentity(5)

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

def crossIdentity(n):
  
  if (n>2):
    a = np.zeros((n,n),dtype = int)
    a[n//2,:] = 1
    a[:,n//2] = 1
    print(a)
  else:
    print("Enter an odd positive number greater than 2")

Arithmetic Operations